config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :pages

  get '/add', to: 'pages#new'
  post '/add', to: 'pages#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
  before_save :refactor_body
  before_update :refactor_body

  TITLEPAGE_FORMAT = /\A[а-яА-ЯёЁa-zA-Z0-9_]+\z/

  validates :title, presence: true, format: { with: TITLEPAGE_FORMAT }
  validates :header, presence: true
  validates :body, presence: true

  has_ancestry

  def refactor_body
    self.body = body.gsub(/\*\*(?<text>.*)\*\*/, '<b>\k<text></b>')
    self.body = body.gsub(/\\\\(?<text>.*)\\\\/, '<i>\k<text></i>')
    self.body = body.gsub(/\(\((?<site>.*) (?<text>.*)\)\)/, '<a href="/\k<site>">\k<text></a>')

    self.body.html_safe
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: %i[show edit update destroy]
  def index
    @pages = Page.all
  end

  def new
    @page = Page.new(parent_id: params[:parent_id])
    @pages = Page.all
  end

  def create
    @page = Page.new(page_params)

    if @page.save
      redirect_to @page, notice: 'Successfully created'
    else
      render :new
    end
  end

  def update
    if @page.update(page_params)
      redirect_to @page, notice: 'Page was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @page.destroy
    redirect_to root_path, notice: 'Successfully destroyed'
  end

  private

  def set_page
    @page = Page.find(params[:id])
  end

  def page_params
    params.require(:page).permit(:title, :header, :body, :parent_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def nested_pages(pages)
    pages.map do |page, sub_pages|
      render(page) + content_tag(:div, nested_pages(sub_pages), class: 'nested_pages')
    end.join.html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Pages" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <%= link_to 'Pages', root_path, class: 'navbar-brand' %>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <%= bootstrap_flash %>
        <%= yield %>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2021</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with model: page do |form| %>

  <%= form.hidden_field :parent_id %>
  
  <div>
    <%= form.label :title if @page.new_record? %><br>
    <%= form.text_field :title if @page.new_record? %>
  </div>

  <div>
    <%= form.label :header %><br>
    <%= form.text_field :header %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_field :body, class: 'form_control', size: '80x10' %>    
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/_page.html.erb
<%= link_to page.title, page %>
<span class="badge"><%= page.children.size %></span>
<%= link_to "Add subpage", new_page_path(parent_id: page[:id]) %>

app/views/pages/edit.html.erb
<h1>Edit page</h1>

<%= render 'form', page: @page %>

app/views/pages/index.html.erb
<div class="col-md-7">
  <% @pages.each do |page| %>
  <ul>
    <li><%= link_to page.id, page_path(page) %></li>
    <li><%= page.parent_id %></li>
    <li><%= page.title %></li>
    <li>
      <%= link_to 'show', page_path(page), class: 'btn btn-default btn-xs' %>
      <%= link_to 'edit', edit_page_path(page), class: 'btn btn-default btn-xs' %>
      <%= link_to 'destroy', page_path(page), method: :delete,
                  :data => {confirm: 'Are you sure?'},
                  :class => 'btn btn-xs btn-danger' %>
    </li>
  </ul>
<% end %>
</div>

<div class="col-md-5">
  <div class="well">
    <h3>Дерево страниц сайта:</h3>
      <%= nested_pages @pages.arrange(:order => :created_at) %>
  </div>
  <%= link_to "Add root page", add_path, class: 'btn btn-primary' %>
</div>

app/views/pages/new.html.erb
<h1>Add Page</h1>

<%= render 'form', page: @page %>

app/views/pages/show.html.erb
<div class="col-md-7">
  <h3><%= @page.header %></h3>
  <p><%= raw @page.body %></p>

  <ul>
    <li>
      <%= link_to 'edit page', edit_page_path(@page), class: 'btn btn-primary' %>
    </li>
    <li>
      <%= link_to 'delete page', page_path(@page), class: 'btn btn-primary', method: :delete, data: {confirm: 'Are you shure?'} %>
    </li>
    <li>
      <%= link_to "Add new subpage", new_page_path(parent_id: @page[:id]), class: 'btn btn-primary' %>
    </li>
  </ul>
</div>
<div class="col-md-5">
  <div class="well">
    <h3>Дерево под страниц</h3>
      <%= nested_pages @page.subtree.arrange(:order => :created_at) %>
  </div>
</div>